const style = 'solid'

export const IconsTypes = {
  spreadsheets: `fa-${style} fa-file-excel`,
  document: `fa-${style} fa-file-lines`,
  folders: `fa-${style} fa-folder`,
  foldersa: `fa-${style} fa-folder`,
  foldersb: `fa-${style} fa-folder`,
  foldersc: `fa-${style} fa-folder`,
  foldersd: `fa-${style} fa-folder`,
  folderse: `fa-${style} fa-folder`,
  foldersf: `fa-${style} fa-folder`,
  foldersg: `fa-${style} fa-folder`,
  foldersh: `fa-${style} fa-folder`,
  foldersi: `fa-${style} fa-folder`,
  foldersj: `fa-${style} fa-folder`,
  foldersk: `fa-${style} fa-folder`,
  foldersl: `fa-${style} fa-folder`,
  foldersm: `fa-${style} fa-folder`,
  foldersn: `fa-${style} fa-folder`,
  folderso: `fa-${style} fa-folder`,
  foldersp: `fa-${style} fa-folder`,
  foldersq: `fa-${style} fa-folder`,
  foldersr: `fa-${style} fa-folder`,
  folderss: `fa-${style} fa-folder`,
  folderst: `fa-${style} fa-folder`,
  foldersu: `fa-${style} fa-folder`,
  foldersv: `fa-${style} fa-folder`,
  foldersw: `fa-${style} fa-folder`,
  foldersx: `fa-${style} fa-folder`,
  foldersy: `fa-${style} fa-folder`,
  foldersz: `fa-${style} fa-folder`,
  folderszz: `fa-${style} fa-folder`,
  foldersaa: `fa-${style} fa-folder`,
  foldersbb: `fa-${style} fa-folder`,
  folderstcc: `fa-${style} fa-folder`,
  folderscc: `fa-${style} fa-folder`,
  foldersee: `fa-${style} fa-folder`,
  foldersxx: `fa-${style} fa-folder`,
  foldersy12: `fa-${style} fa-folder`,
  foldersz12: `fa-${style} fa-folder`,
  folderszz12: `fa-${style} fa-folder`,
  foldersaa12: `fa-${style} fa-folder`,
  foldersbb12: `fa-${style} fa-folder`,
  folderstcc12: `fa-${style} fa-folder`,
  folderscc12: `fa-${style} fa-folder`,
  foldersee12: `fa-${style} fa-folder`,
}